/**
 * Order constants for order actions
 * @module src/Orders/orderConstants
 */

/** START - Constants for Order Action */
const ORDERS_GETALL_REQUEST = 'ORDERS_GETALL_REQUEST';
const ORDERS_GETALL_SUCCESS = 'ORDERS_GETALL_SUCCESS';
const ORDERS_GETALL_FAILURE = 'ORDERS_GETALL_FAILURE';

const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST';
const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
const ORDER_DELETE_FAILURE = 'ORDER_DELETE_FAILURE';


const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

/** END - Constants for Order Action */

const orderConstants = {
	ORDERS_GETALL_REQUEST,
	ORDERS_GETALL_SUCCESS,
	ORDERS_GETALL_FAILURE,
	ORDER_DELETE_REQUEST,
	ORDER_DELETE_SUCCESS,
	ORDER_DELETE_FAILURE,
	CREATE_ORDER_REQUEST,
	CREATE_ORDER_SUCCESS,
	CREATE_ORDER_FAILURE,
};

export default orderConstants;
