const GETALL_REQUEST = 'PRODUCTS_GETALL_REQUEST';
const GETALL_SUCCESS = 'PRODUCTS_GETALL_SUCCESS';
const GETALL_FAILURE = 'PRODUCTS_GETALL_FAILURE';


const productConstants = {
	GETALL_REQUEST,
	GETALL_SUCCESS,
	GETALL_FAILURE,
};

export default productConstants;
